export const FETCH_LADDER_START = 'FETCH_LADDER_START';
export const FETCH_LADDER_SUCCSESS = 'FETCH_LADDER_SUCCSESS';
export const FETCH_LADDER_FAILURE = 'FETCH_LADDER_FAILURE';
export const FETCH_LIKES_SUCCSESS = 'FETCH_LIKES_SUCCSESS';
export const POST_LIKES_SUCCSESS = 'POST_LIKES_SUCCSESS';